export const questions = [
    "Tell me about loss-versus-rebalancing (LVR)",
    "How do L2 sequencers work?",
    "Do an exhaustive breakdown of the MEV supply chain",
    "What is enshrined Proposer Builder Separation (ePBS)?",
    "What is SUAVE?",
    "Give me the most exhaustive definition of loss-versus-rebalancing (LVR)",
    "What are intents?",
    "What are the papers that deal with LVR?",
    "What are solutions to mitigate front-running and sandwich attacks?",
    "Give me several sources about L2 sequencing",
    "Give me several sources about SUAVE",
    "Tell me about transaction ordering on L2s",
    "What are Order Flow Auctions (OFAs)?",
    "Can you tell me how the definition of MEV evolved over the years?",
    "What is MEV burn?",
    "What is account abstraction?",
    "What is ERC-4337?",
    "What is EIP-1559?",
    "How will account abstraction affect the MEV supply chain?",
    "What is the difference between account abstraction and intents?",
    "Is it bad that MEV is a centralizing force?",
    "Tell me about MEV on Solana",
    "Explain to me the differences between Uniswap v2, v3 and v4",
    "What are commit/reveal schemes?",
    "What is the impact of latency in MEV?",
    "What is Protocol enforced Proposer commitments (PEPC)?",
    "Are roll-ups real?",
    "Are intents real?",
    "What are relays?",
    "How does MEV compare across chains for instance Ethereum, Solana, Arbitrum?",
    "What are payment for order flows in MEV?",
    "What is Anoma?",
    "What are shared sequencers?",
    "What is Trusted Execution Environment (TEE)?",
    "What is Multi Party Computation (MPC)?",
    "How does Trusted Execution Environment (TEE) and Multi Party Computation (MPC) relate to MEV?",
    "What is Ethereum alignment?",
    "Return a selection of papers and videos that will introduce me to MEV",
    "What is the role of the Ethereum Foundation?",
    "How does Flashbots contribute to the MEV space?",
    "What is atomic composability?",
    "What are the main advantages and challenges that decentralised finance face relative to traditional finance?",
    "What is the number one thing which make decentralised finance better than traditional finance and why?",
    "What is referred to as good versus bad MEV? How would you explain that to a layman?",
    // "What are the consensus trade-offs that a protocol must make between MEV and decentralization?",
    // "What are the consensus trade-offs that a protocol must make to obtain a higher transaction throughput?",
    "What are credible commitments?",
    "What is at the intersection of AI and crypto?",
    // "Would a spot ETH ETF be good for the crypto ecosystem? Would that be a centralising force?",
    "How can auction theory be used to design a better MEV auction?",
    "What are all the subjects that are needed to understand MEV?",
    "What are all the subjects you are an expert in?",
    "What is MEV-Share?",
    "What is MEV-Boost?",
    "What is a builder?",
    "What is a searcher?",
    "What is a validator?",
    "What is an attester?",
    "How do searchers, builders, relays and validators interact with one another?",
    "How can the user initiating a transaction get shielded from MEV?",
    "Give me lectures links about mechanism design",
    "Give me videos links with Hasu",
    "Give me videos links with Robert Miller",
    "Give me videos links with Jon Charbonneau",
    "Give me videos links with Barnabe Monnot",
    "Give me content from Tarun Chitra",
    "Give me videos links with Dan Robinson",
    "Give me videos about Trusted Execution Environment (TEE)",
    "Give me videos about Order Flow Auctions (OFAs)",
    "Give me videos about intents",
    "Give me videos discussing Uniswap v4",
    "What are the contributions of Jason Milionis to research?",
    "What are the contributions of Ciamac Moallemi to LVR and MEV?",
    "What's an automated market maker (AMM)?",
    "What are the different types of AMMs?",
    "What are Uniswap v4 hooks and do you have some examples?",
    "What is the mempool?",
    "How do private mempools influence MEV?",
    "What is the difference between a private mempool and a dark pool?",
    "What protections can we use against MEV?"
  ]
  